use anyhow::{Context, Result, bail};
use arc_swap::ArcSwap;
use esp_idf_svc::eventloop::EspSystemEventLoop;
use esp_idf_svc::hal::gpio::{Input, PinDriver, Pull};
use esp_idf_svc::hal::peripherals::Peripherals;
use esp_idf_svc::http::client::{Configuration as HttpConfig, EspHttpConnection, Method};
use esp_idf_svc::nvs::EspDefaultNvsPartition;
use esp_idf_svc::timer::EspTaskTimerService;
use log::{info, warn};
use std::fs::File;
use std::io::{Read, Write};
use std::sync::Arc;

use crate::audio_worker::{AudioFrame, AUDIO_QUEUE_DEPTH};
use crate::ffi;
use crate::speaker::Speaker;
use crate::power::InactivityTimer;
use crate::video::{FaceBox, VideoPipeline};
use crate::biometrics::GroupMember;

// Sleep Parameters (wake pins live in power.rs)
const INACTIVITY_TIMEOUT_SECS: u64 = 180;  // 3 mins
const TEMPLATE_ENDPOINT: &str = "http://192.168.1.100:8080/api/v1/members";

// Force 16-byte alignment required by ESP32-P4 ESP-DL hardware acceleration
#[repr(C, align(16))]
struct AlignedModel<const N: usize>([u8; N]);

const RAW_MODEL_BYTES: &[u8; include_bytes!("../assets/mobilefacenet_quantized.espdl").len()] =
    include_bytes!("../assets/mobilefacenet_quantized.espdl");

static MODEL_WEIGHTS: AlignedModel<{ RAW_MODEL_BYTES.len() }> = AlignedModel(*RAW_MODEL_BYTES);

// FFI types are generated by bindgen from biometrics_wrapper.h (see build.rs / crate::ffi)
pub type P4HardwareConfig = ffi::p4_hardware_config_t;
pub type P4CameraFrame = ffi::p4_camera_frame_t;

impl P4CameraFrame {
    pub fn as_slice(&self) -> Option<&[u16]> {
        if self.data.is_null() || self.data_len == 0 {
            return None;
        }
        let pixel_count = (self.width as usize) * (self.height as usize);
        // Safety: the V4L2 buffer stays valid until p4_camera_release_frame()
        unsafe { Some(std::slice::from_raw_parts(self.data as *const u16, pixel_count)) }
    }
}

#[allow(dead_code)] // TODO: populate from ETHERNET_EVENT_* / IP_EVENT_ETH_GOT_IP
pub struct EthernetSession {
    pub is_connected: bool,
    pub ip_address: Option<String>,
}

/// Lifetime-free system resources container
pub struct SystemResources {
    // Service handles held for the program lifetime (taking them initializes the underlying IDF services)
    _nvs: EspDefaultNvsPartition,
    _event_loop: EspSystemEventLoop,
    _timer_service: EspTaskTimerService,
    pub video_pipeline: VideoPipeline,
    pub admin_button: PinDriver<'static, Input>,

    // Inactivity watchdog timer handle
    pub inactivity_timer: InactivityTimer,

    // Bounded mic frame queue; frames are dropped when nobody drains it
    #[allow(dead_code)] // TODO: drained by the voice pipeline
    pub audio_rx: std::sync::mpsc::Receiver<AudioFrame>,

    // Shared between Core 0 (Network) and Core 1 (Matcher)
    pub group_members: Arc<ArcSwap<Vec<GroupMember>>>,

    // Peripheral Handles & Session State
    #[allow(dead_code)] // TODO: success chime on match
    pub speaker: Speaker,
    #[allow(dead_code)] // TODO: populated from Ethernet events
    pub net_session: EthernetSession,

    // Zero-copy camera metadata struct passed to C
    pub raw_frame: P4CameraFrame,
    frame_valid: bool,

    pub fail_count: u32,
}

pub struct SystemResourcesBuilder {
    peripherals: Peripherals,
}

impl SystemResourcesBuilder {
    pub fn new() -> Result<Self> {
        let peripherals = Peripherals::take()
            .context("SystemResources Failed to take ESP32-P4 peripherals")?;
        Ok(Self { peripherals })
    }

    pub fn build(self) -> Result<SystemResources> {
        // 1. Base Service Handlers
        let nvs = EspDefaultNvsPartition::take()
            .context("[SystemResources] Failed to take default NVS partition")?;
        let event_loop = EspSystemEventLoop::take()
            .context("[SystemResources] Failed to take system event loop")?;
        let timer_service = EspTaskTimerService::new()
            .context("[SystemResources] Failed to create task timer service")?;

        // 2. Unified BSP Board Hardware (Display, Camera, I2C, Power)
        let config = P4HardwareConfig {
            display_width: 1280,
            display_height: 720,
            camera_width: 1280,
            camera_height: 720,
        };
        let init_ret = unsafe { ffi::p4_hardware_init_all(&config) };
        if init_ret != 0 {
            bail!("[SystemResources] p4_hardware_init_all failed: {}", init_ret);
        }

        // 3. Audio Subsystem & Worker
        //init_audio_subsystem()
        //    .context("[SystemResources] initializes audio system")?;
        let (audio_tx, audio_rx) = std::sync::mpsc::sync_channel::<AudioFrame>(AUDIO_QUEUE_DEPTH);
        crate::audio_worker::spawn_audio_capture_thread(0, audio_tx);
        let speaker = Speaker::new(0);

        // 4. Admin Button (Pure Rust PinDriver on GPIO0)
        let admin_button = PinDriver::input(self.peripherals.pins.gpio0, Pull::Up)
            .context("[SystemResources] Failed to configure GPIO0 as admin button input")?;

        // 5. Inactivity Watchdog
        let inactivity_timer = InactivityTimer::new();
        crate::power::spawn_inactivity_watchdog(inactivity_timer.clone(), INACTIVITY_TIMEOUT_SECS);
        info!("[SystemResources] Power Inactivity watchdog active (Timeout: {}s)", INACTIVITY_TIMEOUT_SECS);

        // 6. Neural Model Setup
        let model: &'static [u8] = &MODEL_WEIGHTS.0;
        info!("[ESP-DL] MobileFaceNet model mapped at flash addr {:p} (Size: {} bytes)", model.as_ptr(), model.len());

        let dl_err = unsafe { ffi::dl_mobilefacenet_init(model.as_ptr(), model.len()) };
        if dl_err != 0 {
            bail!("[SystemResources] MobileFaceNet Init Failed with code: {}", dl_err);
        }

        info!("[SystemResources] All hardware subsystems and LVGL 9 split-screen ready!");
        Ok(SystemResources {
            _nvs: nvs,
            _event_loop: event_loop,
            _timer_service: timer_service,
            speaker,
            inactivity_timer,
            audio_rx,
            admin_button,
            video_pipeline: VideoPipeline::new(),
            group_members: Arc::new(ArcSwap::from_pointee(Vec::new())),
            net_session: EthernetSession {
                is_connected: false,
                ip_address: None,
            },
            raw_frame: P4CameraFrame::default(),
            frame_valid: false,
            fail_count: 0,
        })
    }
}

impl SystemResources {
    pub fn builder() -> Result<SystemResourcesBuilder> {
        SystemResourcesBuilder::new()
    }

    /// Captures the frame into the C driver buffer.
    /// `&mut self` borrow ENDS instantly upon return.
    pub fn capture_camera_frame(&mut self) -> bool {
        let ret = unsafe { ffi::p4_camera_capture_frame(&mut self.raw_frame, 100) };
        if ret == 0 && !self.raw_frame.data.is_null() {
            self.frame_valid = true;
            true
        } else {
            self.frame_valid = false;
            false
        }
    }

    pub fn release_camera_frame(&mut self) {
        if self.frame_valid {
            unsafe {
                ffi::p4_camera_release_frame(&self.raw_frame);
            }
            self.frame_valid = false;
        }
    }

    pub fn detect_faces(&self, _frame: &[u16]) -> Vec<FaceBox> {
        // Run ESP-DL MobileFaceNet pass
        vec![]
    }

    pub fn is_admin_pressed(&self) -> bool {
        self.admin_button.is_low()
    }

    pub fn is_touch_pressed(&self) -> bool {
        unsafe { ffi::p4_touch_is_pressed() }
    }

    /// Fetch group members over network with local Flash fallback
    pub fn fetch_runtime_templates(&mut self) -> Result<()> {
        info!("Attempting HTTP template fetch from: {}", TEMPLATE_ENDPOINT);

        match self.download_members_http() {
            Ok(members) => {
                info!("Successfully fetched {} members over network.", members.len());
                let _ = Self::save_members_to_flash("/spiffs/members.json", &members);
                self.group_members.store(Arc::new(members));
                Ok(())
            }
            Err(err) => {
                warn!("HTTP fetch failed ({:?}). Loading local Flash backup...", err);
                let cached_members = Self::load_members_from_flash("/spiffs/members.json")?;
                self.group_members.store(Arc::new(cached_members));
                Ok(())
            }
        }
    }

    /// HTTP GET stream downloader using EspHttpConnection directly
    pub fn download_members_http(&self) -> Result<Vec<GroupMember>> {
        let mut connection = EspHttpConnection::new(&HttpConfig {
            use_global_ca_store: false,
            buffer_size: Some(1024),
            buffer_size_tx: Some(1024),
            ..Default::default()
        })
        .context("Failed to build HTTP connection handle")?;

        connection
            .initiate_request(Method::Get, TEMPLATE_ENDPOINT, &[])
            .context("Failed to initiate GET request")?;

        connection
            .initiate_response()
            .context("Failed to receive HTTP response")?;

        let status = connection.status();
        if status != 200 {
            bail!("HTTP GET failed with status code: {}", status);
        }

        let mut buf = Vec::new();
        let mut chunk = [0u8; 512];
        loop {
            let bytes_read = connection.read(&mut chunk)?;
            if bytes_read == 0 {
                break;
            }
            buf.extend_from_slice(&chunk[..bytes_read]);
        }

        let members: Vec<GroupMember> =
            serde_json::from_slice(&buf).context("Failed to deserialize JSON member payload")?;

        Ok(members)
    }

    pub fn save_members_to_flash(path: &str, members: &[GroupMember]) -> Result<()> {
        let json = serde_json::to_vec(members)?;
        let mut file = File::create(path)?;
        file.write_all(&json)?;
        Ok(())
    }

    pub fn load_members_from_flash(path: &str) -> Result<Vec<GroupMember>> {
        let mut file = File::open(path)?;
        let mut buf = Vec::new();
        file.read_to_end(&mut buf)?;
        let members: Vec<GroupMember> = serde_json::from_slice(&buf)?;
        Ok(members)
    }

    pub fn extract_face_embedding(&self, face_crop_112x112: &[u8]) -> anyhow::Result<[f32; 512]> {
        if face_crop_112x112.len() != 112 * 112 * 3 {
            anyhow::bail!("Invalid face crop frame size");
        }

        let mut embedding = [0.0f32; 512];

        let err = unsafe {
            ffi::dl_mobilefacenet_run(
                face_crop_112x112.as_ptr(),
                embedding.as_mut_ptr(),
                embedding.len(),
            )
        };

        if err != 0 {
            anyhow::bail!("ESP-DL inference failed with error code: {}", err);
        }

        Ok(embedding)
    }

    pub fn check_ethernet_link_status(&self) -> bool {
        //TODO: KTANG unsafe { ffi::p4_eth_is_link_up() }
        true
    }
}

pub fn validate_running_app() {
    unsafe { ffi::p4_mark_app_valid() };
}

/// Crops a face region from the raw RGB565 camera frame and resizes it to 112x112 RGB888 for ESP-DL
pub fn crop_face_112x112(frame_rgb565: &[u16], frame_w: usize, frame_h: usize, face: &FaceBox) -> Option<Vec<u8>> {

    let bx = (face.x as usize).min(frame_w - 1);
    let by = (face.y as usize).min(frame_h - 1);
    let bw = (face.width as usize).min(frame_w - bx);
    let bh = (face.height as usize).min(frame_h - by);
    
    if bw == 0 || bh == 0 {
        return None;
    }

    let mut crop_rgb888 = vec![0u8; 112 * 112 * 3];

    // Nearest-neighbor crop and RGB565 -> RGB888 conversion
    for dy in 0..112 {
        let sy = by + (dy * bh) / 112;
        for dx in 0..112 {
            let sx = bx + (dx * bw) / 112;
            let pixel_565 = frame_rgb565[sy * frame_w + sx];

            // Extract RGB channels
            let r = (((pixel_565 >> 11) & 0x1F) as u8) << 3;
            let g = (((pixel_565 >> 5) & 0x3F) as u8) << 2;
            let b = ((pixel_565 & 0x1F) as u8) << 3;

            let out_idx = (dy * 112 + dx) * 3;
            crop_rgb888[out_idx] = r;
            crop_rgb888[out_idx + 1] = g;
            crop_rgb888[out_idx + 2] = b;
        }
    }

    Some(crop_rgb888)
}