[build]
target = "riscv32imafc-esp-espidf"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "espflash flash --monitor --partition-table partitions.csv"
rustflags = [
  "-C", "link-arg=-Wl,--undefined=app_main"
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32p4"
ESP_IDF_VERSION = "v5.4.4"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"
ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", force = true }
PYTHON = "/opt/homebrew/bin/python3.12"