use embuild::build::LinkArgs;

fn main() {
    // Rust FFI bindings for components/biometrics_wrapper are generated by esp-idf-sys
    // (see `bindings_header` in Cargo.toml). Note: esp-idf-sys only re-runs CMake when
    // sdkconfig.defaults changes, so `touch sdkconfig.defaults` after C++/header edits.
    println!("cargo:rerun-if-changed=sdkconfig.defaults");

    // Propagate ESP-IDF build flags and linker configuration
    LinkArgs::output_propagated("ESP_IDF").expect("Failed to propagate link args");

    // Ensure C++ standard library is explicitly linked for biometrics_wrapper
    println!("cargo:rustc-link-arg=-lstdc++");
}
